export const articlePath = '/minds-in-action/the-bias-isnt-in-you'
export const author = 'Willva Iriana Alberto'
export const portrait = '/assets/authors/willva-alberto.jpeg'

export const article = {
  en: {
    title: "The Bias isn't in You; it's in the Camera",
    subtitle: 'Every shade deserves the right light.',
    category: 'Technology',
    bio: 'Digital Marketing graduate · Ravensbourne University London',
    sections: [
      { id: 'introduction', title: 'Introduction', paragraphs: [
        'My name is Willva Iriana Alberto, and I am a recent graduate in Digital Marketing from Ravensbourne University London. My final project, which received a First-Class grade, was focused on investigating the inefficiency of cameras when capturing people with darker skin tones and exploring the solutions emerging within cutting-edge technology.',
        "I always found myself questioning: why do cameras still struggle with skin tones? In this article I will summarize some of what I found and will give you a brief insight on how this issue, that has been present for many years, could possibly now be solved through my idea.",
      ] },
      { id: 'the-problem', title: 'The Problem', paragraphs: [
        'So where does this come from? Through my research, I found an article written by Lorna Roth, a professor at Concordia University for communications studies in 2009, called Looking at Shirley, the Ultimate Norm: Colour Balance, Image Technologies, and Cognitive Equity; that confirmed to me that cameras were never really built with darker skin in mind in the first place.',
        'Roth explains that when film cameras were first developed, Kodak calibrated them using what were called "Shirley cards," basically reference photos of white-skinned women that became the industry standard for exposure and colour. That means the entire foundation of photography technology was built around lighter skin, and darker-skinned people were left underexposed and misrepresented from the very beginning, not because of a mistake, but because it just wasn\'t considered. And honestly, it took until 1995 for Kodak to even introduce a multi-racial reference card, so this wasn\'t a quick fix, it took decades.',
        "What's even more frustrating is that this isn't just an old, outdated problem. Joy Buolamwini is a Canadian American woman who did a Gender Shades project in 2018 where she found that even now, with all the technology we have, facial recognition and imaging systems still perform worse for darker-skinned people, especially darker-skinned women, who had the highest error rates out of everyone tested. So, all this technology has moved forward, but somehow this specific issue hasn't really been fixed, which tells me that inclusivity was never really built in as a priority, it's always been an afterthought.",
      ] },
      { id: 'why-it-matters', title: 'Why It Matters', paragraphs: [
        "If you have ever felt like you had to retake pictures more than once because your skin tone felt altered or you simply weren't seen in a picture, you know it's extremely upsetting. To me, this isn't just a technical flaw I found in some research paper, it's something I've lived. Growing up as a Black girl in a European city where most people around me weren't of colour, I know exactly what it feels like to look at a picture of yourself and feel like the camera just didn't see you properly, like you were somehow left out of your own photo. I genuinely hated having my picture taken as a kid, because I was always the student the teacher or photographer had to change the settings for, and it would take longer with me, which left me feeling extremely uncomfortable, like I was the problem. On top of that, in group pictures, I would barely appear properly. That's heartbreaking to me, because those are memories you want to keep forever, but because the technology simply wasn't advanced enough for people like me yet, I just had to accept it, and that's frustrating. My research wasn't shocking to me; it simply confirmed something I had already felt for years.",
        "And I'm not the only one; through conversations with people around me, I found that being photographed or recorded can trigger real self-consciousness across all kinds of people, from students presenting in class to entrepreneurs trying to build a personal brand online, and a big part of that anxiety comes down to the fear that the camera simply won't represent them accurately or favourably. I think it stops being just my experience and becomes a much bigger issue, because if facial recognition and imaging systems are still misreading darker-skinned faces at significantly higher error rates, that's not just about a bad selfie, that's bias built into technology that's increasingly used in security, hiring, healthcare, and everyday life.",
        "It's worth noting that companies like Google and Apple have started adjusting in this direction, which only proves this was always a real problem worth solving, but in the camera market specifically, it's barely been addressed at all. That gap, between how normalised this issue is and how little has been done about it, is exactly why I felt this couldn't just be a research topic for me, it had to become something I tried to find a way to solve.",
      ] },
      { id: 'solutions', title: 'Solutions', paragraphs: [
        "So, what could fix this? Big tech has already proven it's solvable. Google's Real Tone, built into devices like the Pixel 6 Pro, uses the Monk Skin Tone Scale, developed with Harvard sociologist Dr. Ellis Monk, to better capture darker skin tones, and it outperformed rival cameras in testing. Apple has made similar moves.",
        'So, the technology exists, it just hasn\'t reached the camera market yet, and that\'s where my brand comes in, named AuraCam, with the tagline of "confidence in every shot". It\'s supposed to be a camera that dynamically calibrates exposure, white balance, and colour based on the actual skin tones in frame, in real time. It\'s not a filter, it\'s the camera finally seeing everyone accurately. I chose to add AI features like automatic lighting correction, background cleanup, and real-time framing to remove the technical excuses that make people, especially Gen Z creators, anxious on camera.',
      ] },
      { id: 'conclusion', title: 'Conclusion', paragraphs: [
        "At the end of the day, this project was never just about building a camera concept, it was about proving a point I've felt my whole life: the bias was never in me, it was in the technology. Confidence shouldn't depend on your skin tone, and if the industry's biggest names can already show this is fixable, then there's no excuse for it to stay this way, in phones or in cameras. That's the standard my fictitious brand was meant to meet. I hope sincerely that anyone who felt affected in any way shape or form, reading this knows that this issue has a solution and I have it as my mission to help make it become real.",
      ] },
    ],
  },
  pt: {
    title: 'O preconceito não está em ti; está na câmara',
    subtitle: 'Cada tom de pele merece a luz certa.',
    category: 'Tecnologia',
    bio: 'Licenciada em Marketing Digital · Ravensbourne University London',
    sections: [
      { id: 'introduction', title: 'Introdução', paragraphs: [
        'Chamo-me Willva Iriana Alberto e sou recém-licenciada em Marketing Digital pela Ravensbourne University London. O meu projeto final, que recebeu a classificação de First-Class, centrou-se na investigação da ineficiência das câmaras ao captar pessoas com tons de pele mais escuros e na exploração das soluções que estão a surgir na tecnologia de ponta.',
        'Sempre dei por mim a perguntar: porque é que as câmaras continuam a ter dificuldades com os tons de pele? Neste artigo, vou resumir algumas das minhas descobertas e dar uma breve perspetiva de como este problema, que existe há muitos anos, poderá agora encontrar uma solução através da minha ideia.',
      ] },
      { id: 'the-problem', title: 'O problema', paragraphs: [
        'De onde vem, então, este problema? Durante a minha investigação, encontrei um artigo de 2009 de Lorna Roth, professora de Estudos de Comunicação na Concordia University, intitulado Looking at Shirley, the Ultimate Norm: Colour Balance, Image Technologies, and Cognitive Equity. O artigo confirmou-me que, desde o início, as câmaras nunca foram verdadeiramente concebidas a pensar nas peles mais escuras.',
        'Roth explica que, quando as câmaras de película foram desenvolvidas, a Kodak calibrava-as com os chamados «cartões Shirley»: fotografias de referência de mulheres de pele branca que se tornaram o padrão da indústria para a exposição e a cor. Isto significa que toda a base da tecnologia fotográfica foi construída em torno de peles mais claras, deixando as pessoas de pele mais escura subexpostas e mal representadas desde o início — não por engano, mas porque simplesmente não foram tidas em conta. E, sinceramente, só em 1995 é que a Kodak introduziu um cartão de referência multirracial. Não foi, portanto, uma correção rápida: demorou décadas.',
        'O mais frustrante é que este não é apenas um problema antigo e ultrapassado. Joy Buolamwini, uma mulher canadiana-americana, realizou em 2018 o projeto Gender Shades, no qual verificou que, mesmo com toda a tecnologia de que dispomos, os sistemas de reconhecimento facial e de imagem continuam a ter um desempenho inferior com pessoas de pele mais escura. Isto afeta sobretudo as mulheres de pele mais escura, que apresentaram as taxas de erro mais elevadas entre todas as pessoas testadas. Toda esta tecnologia avançou, mas este problema específico continua, de alguma forma, por resolver. Para mim, isto mostra que a inclusão nunca foi integrada como prioridade: foi sempre algo em que se pensou depois.',
      ] },
      { id: 'why-it-matters', title: 'Porque é importante', paragraphs: [
        'Se alguma vez sentiste que tinhas de repetir fotografias porque o teu tom de pele parecia alterado, ou porque simplesmente não se conseguia ver-te na imagem, sabes como isso é profundamente perturbador. Para mim, não se trata apenas de uma falha técnica que encontrei num artigo científico: é algo que vivi. Crescer como uma rapariga negra numa cidade europeia onde a maioria das pessoas à minha volta não era racializada fez-me conhecer bem a sensação de olhar para uma fotografia minha e sentir que a câmara não me tinha visto como devia, como se eu tivesse ficado de fora da minha própria fotografia. Em criança, detestava mesmo que me tirassem fotografias, porque era sempre a aluna para quem o professor ou o fotógrafo tinha de alterar as definições. Comigo demorava mais, e isso deixava-me extremamente desconfortável, como se o problema fosse eu. Além disso, nas fotografias de grupo, mal se conseguia ver-me devidamente. Isso parte-me o coração, porque são memórias que queremos guardar para sempre. Mas, como a tecnologia ainda não era suficientemente avançada para pessoas como eu, tinha simplesmente de aceitar. E isso é frustrante. A minha investigação não me chocou: limitou-se a confirmar algo que já sentia há anos.',
        'E não sou a única. Através de conversas com pessoas à minha volta, percebi que ser fotografado ou filmado pode provocar uma insegurança real em todo o tipo de pessoas, desde estudantes a fazer apresentações nas aulas até empreendedores a construir uma marca pessoal online. Uma grande parte dessa ansiedade vem do receio de que a câmara não os represente de forma fiel ou favorável. Penso que isto deixa de ser apenas a minha experiência e passa a ser um problema muito maior: se os sistemas de reconhecimento facial e de imagem continuam a interpretar incorretamente rostos de pele mais escura, com taxas de erro significativamente superiores, já não estamos apenas a falar de uma má selfie. Estamos a falar de preconceito incorporado numa tecnologia cada vez mais utilizada na segurança, no recrutamento, nos cuidados de saúde e na vida quotidiana.',
        'Vale a pena referir que empresas como a Google e a Apple começaram a fazer ajustes neste sentido, o que só confirma que este sempre foi um problema real que merecia ser resolvido. Mas, especificamente no mercado das câmaras, quase nada foi feito. Esta distância entre o quanto o problema está normalizado e o pouco que se tem feito para o resolver foi precisamente o que me levou a sentir que isto não podia ser apenas um tema de investigação: tinha de se tornar algo para o qual eu tentasse encontrar uma solução.',
      ] },
      { id: 'solutions', title: 'Soluções', paragraphs: [
        'O que poderia, então, resolver este problema? As grandes empresas tecnológicas já provaram que é possível. O Real Tone da Google, integrado em dispositivos como o Pixel 6 Pro, utiliza a Monk Skin Tone Scale, desenvolvida com o sociólogo de Harvard Dr. Ellis Monk, para captar melhor os tons de pele mais escuros, tendo superado câmaras concorrentes em testes. A Apple tem dado passos semelhantes.',
        'A tecnologia existe; simplesmente ainda não chegou ao mercado das câmaras. É aqui que entra a minha marca, a AuraCam, com o lema «confiança em cada fotografia». A ideia é uma câmara que calibra dinamicamente a exposição, o balanço de brancos e a cor com base nos tons de pele reais presentes no enquadramento, em tempo real. Não é um filtro: é a câmara a conseguir, finalmente, ver todas as pessoas com fidelidade. Optei por acrescentar funcionalidades de inteligência artificial, como a correção automática da iluminação, a limpeza do fundo e o enquadramento em tempo real, para eliminar as dificuldades técnicas que deixam as pessoas, sobretudo os criadores da Geração Z, ansiosas perante a câmara.',
      ] },
      { id: 'conclusion', title: 'Conclusão', paragraphs: [
        'No fundo, este projeto nunca foi apenas sobre criar um conceito de câmara. Foi sobre demonstrar algo que senti durante toda a minha vida: o preconceito nunca esteve em mim, esteve na tecnologia. A confiança não devia depender do tom de pele e, se os maiores nomes da indústria já conseguem mostrar que isto tem solução, não há desculpa para que continue assim, nos telemóveis ou nas câmaras. Foi esse o padrão que a minha marca fictícia procurou alcançar. Espero sinceramente que qualquer pessoa que se tenha sentido afetada, de alguma forma, saiba, ao ler este artigo, que este problema tem solução. E tenho como missão ajudar a torná-la realidade.',
      ] },
    ],
  },
}

export function readingMinutes(lang: 'en' | 'pt') {
  const words = article[lang].sections.flatMap(s => s.paragraphs).join(' ').split(/\s+/).length
  return Math.max(1, Math.ceil(words / 200))
}

// Planned publication date; shared by the listing and article header.
export const publishedDate = '2026-09-24'
export function publicationLabel(lang: 'en' | 'pt') {
  return new Intl.DateTimeFormat(lang === 'pt' ? 'pt-PT' : 'en-GB', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${publishedDate}T12:00:00Z`))
}
